version: "2"
checks:
  # wow this check is so bad
  # infinity false positives
  similar-code:
    enabled: false

  # this check is just dumb: early exits are good, not bad
  return-statements:
    enabled: false
